### SignIn (Form)
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username = {{username}} &
password = {{password}}

### Create Account with Risk Type(FULL_BALANCE, HALF_BALANCE)
POST {{host}}/accounts
Content-Type: application/json

{
  "riskType": "FULL_BALANCE"
}

> {%
  const account = response.body;
  client.global.set("accountId", account.accountId);
%}

### Account
GET {{host}}/accounts
Content-Type: application/json

### Deposit
POST {{host}}/accounts/{{accountId}}/deposit
Content-Type: application/json

{
  "amount": 100000000
}

### Withdraw
POST {{host}}/accounts/{{accountId}}/withdraw
Content-Type: application/json

{
  "amount": 1000
}

### Advisory
POST {{host}}/accounts/{{accountId}}/advisory