### SignIn (Form)
POST {{host}}/login
Content-Type: application/x-www-form-urlencoded

username={{username}}&password={{password}}

### Create a new security
POST {{host}}/securities
Content-Type: application/json

{
  "name": "기아",
  "ticker": "000270",
  "price": 87800
}

### Update a security
PUT {{host}}/securities/000270/price
Content-Type: application/json

{
  "price": 88000
}

### Delete a security
DELETE {{host}}/securities/000270